packages:
  - apps/*
  - packages/*
  - packages/config/*
  - packages/design-system/*

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@scarf/scarf'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - msgpackr-extract
  - sharp
  - unrs-resolver
